Pin python version to 3.12
Chart linter is failing with error `AttributeError: module 'ast' has no attribute 'Num'` as ast.Num was planned for removal in Python 3.14.
For details see https://docs.python.org/3/deprecations/pending-removal-in-3.14.html